CREATE DATABASE ASSIGNMENT_P
USE ASSIGNMENT_P;
CREATE TABLE EMPLOYEE(
ID INT,NAME VARCHAR (30),EMAIL VARCHAR(30),SALARY MONEY,DEPT INT FOREIGN KEY REFERENCES DEPT(ID),
GENDER VARCHAR (10), JOINING_DATE DATE);

CREATE TABLE DEPT(ID INT PRIMARY KEY, NAME VARCHAR(30),DESCRIPTION VARCHAR(20));
SELECT*FROM EMPLOYEE;
SELECT*FROM DEPT;
SP_RENAME 'DEPT.NAME','DEPT_NAME','COLUMN';

INSERT INTO DEPT VALUES (1,'HR','MANAGEMENT');
INSERT INTO DEPT VALUES(2,'DEVELOPER','CODING');
INSERT INTO DEPT VALUES(3,'TESTING','SOFTWARE TESTING');
INSERT INTO DEPT VALUES(4,'MARKETING','SELLING');
INSERT INTO DEPT VALUES(5,'SKILL-DEPARTMENT','FOR TRAINING');
--------------
INSERT INTO EMPLOYEE VALUES(101,'AJAY KUMAR','ajay@123gmail.com',30000,5,'MALE','2019-01-01');
INSERT INTO EMPLOYEE VALUES(102,'VINAY KUMAR','vinay@123gmail.com',50000,4,'MALE','2015-01-01');
INSERT INTO EMPLOYEE VALUES(103,'SONU KUMAR','sonu@123gmail.com',35000,3,'MALE','2016-01-01');
INSERT INTO EMPLOYEE VALUES(104,'RIYA KUMARI','riya@123gmail.com',30000,2,'FEMALE','2022-08-01');
INSERT INTO EMPLOYEE VALUES(105,' MEENA SINGH','meena@123gmail.com',39000,2,'FEMALE','2021-09-01');
C:\Users\admin\AppData\Local\Temp\~vs1239.sql